[package]
name = "pie"
version = "0.1.0"
edition = "2024"

[features]
metal = ["worker/metal"]

[dependencies]
anyhow = "1"
bootstrap = { path = "crates/bootstrap" }
chat-template = { path = "crates/chat-template" }
clap = { version = "4", features = ["derive"] }
gateway = { path = "crates/gateway" }
models = { path = "crates/models" }
runtime = { path = "crates/runtime" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
toml = "1"
worker = { path = "crates/worker" }

[workspace]
resolver = "3"
members = [".", "crates/*", "tests/inferlets/*"]
default-members = ["."]

[profile.release]
debug = false
