[package]
name = "pie"
version = "0.1.0"
edition = "2024"

[features]
metal = ["worker/metal"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
runtime = { path = "crates/runtime" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
worker = { path = "crates/worker" }

[workspace]
resolver = "3"
members = [".", "crates/*", "tests/inferlets/*"]
default-members = ["."]

[profile.release]
debug = false
